module.exports = {
  "Principle1.Guideline1_1.1_1_1":
  {
    "category":"0",
    "weigth":"1"
  },
  "Principle1.Guideline1_2.1_2_1":
  {
    "category":"0",
    "weigth":"1"
  },
  "Principle1.Guideline1_2.1_2_2":
  {
    "category":"0",
    "weigth":"1"
  },
  "Principle1.Guideline1_2.1_2_4":
  {
    "category":"0",
    "weigth":"1"
  },
  "Principle1.Guideline1_2.1_2_5":
  {
    "category":"1",
    "weigth":"1"
  },
  "Principle1.Guideline1_2.1_2_6":
  {
    "category":"2",
    "weigth":"1"
  },
  "Principle1.Guideline1_2.1_2_7":
  {
    "category":"1",
    "weigth":"1"
  },
  "Principle1.Guideline1_2.1_2_8":
  {
    "category":"1",
    "weigth":"1"
  },
  "Principle1.Guideline1_2.1_2_9":
  {
    "category":"0",
    "weigth":"1"
  },
  "Principle1.Guideline1_3.1_3_1":
  {
    "category":"0",
    "weigth":"1"
  },
  "Principle1.Guideline1_3.1_3_1_AAA":
  {
    "category":"",
    "weigth":"1"
  },
  "Principle1.Guideline1_3.1_3_2":
  {
    "category":"2",
    "weigth":"1"
  },
  "Principle1.Guideline1_3.1_3_3":
  {
    "category":"3",
    "weigth":"1"
  },
  "Principle1.Guideline1_4.1_4_1":
  {
    "category":"3",
    "weigth":"1"
  },
  "Principle1.Guideline1_4.1_4_2":
  {
    "category":"1",
    "weigth":"1"
  },
  "Principle1.Guideline1_4.1_4_3_F24":
  {
    "category":"4",
    "weigth":"1"
  },
  "Principle1.Guideline1_4.1_4_3_Contrast":
  {
    "category":"4",
    "weigth":"1"
  },
  "Principle1.Guideline1_4.1_4_6":
  {
    "category":"4",
    "weigth":"1"
  },
  "Principle1.Guideline1_4.1_4_7":
  {
    "category":"1",
    "weigth":"1"
  },
  "Principle1.Guideline1_4.1_4_8":
  {
    "category":"3",
    "weigth":"1"
  },
  "Principle1.Guideline1_4.1_4_9":
  {
    "category":"3",
    "weigth":"1"
  },
  "Principle2.Guideline2_1.2_1_1":
  {
    "category":"5",
    "weigth":"1"
  },
  "Principle2.Guideline2_1.2_1_2":
  {
    "category":"5",
    "weigth":"1"
  },
  "Principle2.Guideline2_2.2_2_2":
  {
    "category":"6",
    "weigth":"1"
  },
  "Principle2.Guideline2_2.2_2_3":
  {
    "category":"12",
    "weigth":"1"
  },
  "Principle2.Guideline2_2.2_2_4":
  {
    "category":"12",
    "weigth":"1"
  },
  "Principle2.Guideline2_2.2_2_5":
  {
    "category":"7",
    "weigth":"1"
  },
  "Principle2.Guideline2_3.2_3_2":
  {
    "category":"6",
    "weigth":"1"
  },
  "Principle2.Guideline2_4.2_4_1":
  {
    "category":"12",
    "weigth":"1"
  },
  "Principle2.Guideline2_4.2_4_2":
  {
    "category":"8",
    "weigth":"1"
  },
  "Principle2.Guideline2_4.2_4_3":
  {
    "category":"9",
    "weigth":"1"
  },
  "Principle2.Guideline2_4.2_4_5":
  {
    "category":"9",
    "weigth":"1"
  },
  "Principle2.Guideline2_4.2_4_6":
  {
    "category":"8",
    "weigth":"1"
  },
  "Principle2.Guideline2_4.2_4_7":
  {
    "category":"5",
    "weigth":"1"
  },
  "Principle2.Guideline2_4.2_4_8":
  {
    "category":"9",
    "weigth":"1"
  },
  "Principle2.Guideline2_4.2_4_9":
  {
    "category":"9",
    "weigth":"1"
  },
  "Principle3.Guideline3_1.3_1_1":
  {
    "category":"10",
    "weigth":"1"
  },
  "Principle3.Guideline3_1.3_1_2":
  {
    "category":"10",
    "weigth":"1"
  },
  "Principle3.Guideline3_1.3_1_3":
  {
    "category":"10",
    "weigth":"1"
  },
  "Principle3.Guideline3_1.3_1_4":
  {
    "category":"10",
    "weigth":"1"
  },
  "Principle3.Guideline3_1.3_1_5":
  {
    "category":"10",
    "weigth":"1"
  },
  "Principle3.Guideline3_1.3_1_6":
  {
    "category":"10",
    "weigth":"1"
  },
  "Principle3.Guideline3_2.3_2_1":
  {
    "category":"3",
    "weigth":"1"
  },
  "Principle3.Guideline3_2.3_2_2":
  {
    "category":"12",
    "weigth":"1"
  },
  "Principle3.Guideline3_2.3_2_3":
  {
    "category":"9",
    "weigth":"1"
  },
  "Principle3.Guideline3_2.3_2_4":
  {
    "category":"8",
    "weigth":"1"
  },
  "Principle3.Guideline3_2.3_2_5":
  {
    "category":"",
    "weigth":"1"
  },
  "Principle3.Guideline3_3.3_3_1":
  {
    "category":"5",
    "weigth":"1"
  },
  "Principle3.Guideline3_3.3_3_2":
  {
    "category":"5",
    "weigth":"1"
  },
  "Principle3.Guideline3_3.3_3_3":
  {
    "category":"5",
    "weigth":"1"
  },
  "Principle3.Guideline3_3.3_3_5":
  {
    "category":"8",
    "weigth":"1"
  },
  "Principle3.Guideline3_3.3_3_6":
  {
    "category":"7",
    "weigth":"1"
  },
  "Principle4.Guideline4_1.4_1_1":
  {
    "category":"11",
    "weigth":"1"
  },
  "Principle4.Guideline4_1.4_1_2":
  {
    "category":"11",
    "weigth":"1"
  },
  "AX_ARIA_01":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_ARIA_02":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_ARIA_03":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_ARIA_04":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_ARIA_05":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_ARIA_06":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_ARIA_07":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_ARIA_08":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_ARIA_09":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_ARIA_10":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_ARIA_11":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_ARIA_12":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_ARIA_13":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_AUDIO_01":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_HTML_01":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_HTML_02":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_TEXT_01":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_TEXT_02":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_TEXT_03":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_TEXT_04":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_TITLE_01":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_IMAGE_01":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_FOCUS_01":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_FOCUS_02":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_FOCUS_03":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_COLOR_01":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_VIDEO_01":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_TABLE_01":
  {
    "category":"AX",
    "weigth":"1"
  },
  "AX_TOOLTIP_01":
  {
    "category":"AX",
    "weigth":"1"
  }
}